import { Word } from "./types";

/**
 * 테스트용 데이터
 */

export const mockWords: Record<string, Word[]> = {
  N5: [
    {
      id: "1",
      word: "こんにちは",
      reading: "こんにちは",
      meaning: "Hello, Good afternoon",
      level: "N5",
      part_of_speech: "Greeting",
      example_sentence: "こんにちは、元気ですか。",
      example_reading: "こんにちは、げんきですか。",
      example_translation: "Hello, how are you?",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      word: "ありがとう",
      reading: "ありがとう",
      meaning: "Thank you",
      level: "N5",
      part_of_speech: "Expression",
      example_sentence: "ありがとうございます。",
      example_reading: "ありがとうございます。",
      example_translation: "Thank you very much.",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      word: "学校",
      reading: "がっこう",
      meaning: "School",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "学校に行きます。",
      example_reading: "がっこうにいきます。",
      example_translation: "I go to school.",
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      word: "食べる",
      reading: "たべる",
      meaning: "To eat",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "ご飯を食べます。",
      example_reading: "ごはんをたべます。",
      example_translation: "I eat rice.",
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      word: "水",
      reading: "みず",
      meaning: "Water",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "水を飲みます。",
      example_reading: "みずをのみます。",
      example_translation: "I drink water.",
      created_at: new Date().toISOString(),
    },
    {
      id: "6",
      word: "本",
      reading: "ほん",
      meaning: "Book",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "本を読みます。",
      example_reading: "ほんをよみます。",
      example_translation: "I read a book.",
      created_at: new Date().toISOString(),
    },
    {
      id: "7",
      word: "行く",
      reading: "いく",
      meaning: "To go",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "駅に行きます。",
      example_reading: "えきにいきます。",
      example_translation: "I go to the station.",
      created_at: new Date().toISOString(),
    },
    {
      id: "8",
      word: "来る",
      reading: "くる",
      meaning: "To come",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "友達が来ます。",
      example_reading: "ともだちがきます。",
      example_translation: "My friend comes.",
      created_at: new Date().toISOString(),
    },
    {
      id: "9",
      word: "見る",
      reading: "みる",
      meaning: "To see, To watch",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "テレビを見ます。",
      example_reading: "テレビをみます。",
      example_translation: "I watch TV.",
      created_at: new Date().toISOString(),
    },
    {
      id: "10",
      word: "聞く",
      reading: "きく",
      meaning: "To listen, To hear",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "音楽を聞きます。",
      example_reading: "おんがくをききます。",
      example_translation: "I listen to music.",
      created_at: new Date().toISOString(),
    },
    {
      id: "11",
      word: "話す",
      reading: "はなす",
      meaning: "To speak, To talk",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "日本語を話します。",
      example_reading: "にほんごをはなします。",
      example_translation: "I speak Japanese.",
      created_at: new Date().toISOString(),
    },
    {
      id: "12",
      word: "書く",
      reading: "かく",
      meaning: "To write",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "手紙を書きます。",
      example_reading: "てがみをかきます。",
      example_translation: "I write a letter.",
      created_at: new Date().toISOString(),
    },
    {
      id: "13",
      word: "読む",
      reading: "よむ",
      meaning: "To read",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "新聞を読みます。",
      example_reading: "しんぶんをよみます。",
      example_translation: "I read a newspaper.",
      created_at: new Date().toISOString(),
    },
    {
      id: "14",
      word: "買う",
      reading: "かう",
      meaning: "To buy",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "パンを買います。",
      example_reading: "パンをかいます。",
      example_translation: "I buy bread.",
      created_at: new Date().toISOString(),
    },
    {
      id: "15",
      word: "売る",
      reading: "うる",
      meaning: "To sell",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "車を売ります。",
      example_reading: "くるまをうります。",
      example_translation: "I sell a car.",
      created_at: new Date().toISOString(),
    },
    {
      id: "16",
      word: "飲む",
      reading: "のむ",
      meaning: "To drink",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "お茶を飲みます。",
      example_reading: "おちゃをのみます。",
      example_translation: "I drink tea.",
      created_at: new Date().toISOString(),
    },
    {
      id: "17",
      word: "寝る",
      reading: "ねる",
      meaning: "To sleep",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "夜に寝ます。",
      example_reading: "よるにねます。",
      example_translation: "I sleep at night.",
      created_at: new Date().toISOString(),
    },
    {
      id: "18",
      word: "起きる",
      reading: "おきる",
      meaning: "To wake up, To get up",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "朝に起きます。",
      example_reading: "あさにおきます。",
      example_translation: "I wake up in the morning.",
      created_at: new Date().toISOString(),
    },
    {
      id: "19",
      word: "勉強",
      reading: "べんきょう",
      meaning: "Study",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "勉強します。",
      example_reading: "べんきょうします。",
      example_translation: "I study.",
      created_at: new Date().toISOString(),
    },
    {
      id: "20",
      word: "仕事",
      reading: "しごと",
      meaning: "Work, Job",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "仕事をします。",
      example_reading: "しごとをします。",
      example_translation: "I work.",
      created_at: new Date().toISOString(),
    },
    {
      id: "21",
      word: "友達",
      reading: "ともだち",
      meaning: "Friend",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "友達と遊びます。",
      example_reading: "ともだちとあそびます。",
      example_translation: "I play with friends.",
      created_at: new Date().toISOString(),
    },
    {
      id: "22",
      word: "家",
      reading: "いえ",
      meaning: "House, Home",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "家に帰ります。",
      example_reading: "いえにかえります。",
      example_translation: "I go home.",
      created_at: new Date().toISOString(),
    },
    {
      id: "23",
      word: "駅",
      reading: "えき",
      meaning: "Station",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "駅で待ちます。",
      example_reading: "えきでまちます。",
      example_translation: "I wait at the station.",
      created_at: new Date().toISOString(),
    },
    {
      id: "24",
      word: "電車",
      reading: "でんしゃ",
      meaning: "Train",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "電車に乗ります。",
      example_reading: "でんしゃにのります。",
      example_translation: "I ride the train.",
      created_at: new Date().toISOString(),
    },
    {
      id: "25",
      word: "車",
      reading: "くるま",
      meaning: "Car",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "車を運転します。",
      example_reading: "くるまをうんてんします。",
      example_translation: "I drive a car.",
      created_at: new Date().toISOString(),
    },
  ],
  N4: [
    {
      id: "101",
      word: "経験",
      reading: "けいけん",
      meaning: "Experience",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "経験が必要です。",
      example_reading: "けいけんがひつようです。",
      example_translation: "Experience is necessary.",
      created_at: new Date().toISOString(),
    },
    {
      id: "102",
      word: "意見",
      reading: "いけん",
      meaning: "Opinion",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "あなたの意見を聞かせてください。",
      example_reading: "あなたのいけんをきかせてください。",
      example_translation: "Please let me hear your opinion.",
      created_at: new Date().toISOString(),
    },
    {
      id: "103",
      word: "準備",
      reading: "じゅんび",
      meaning: "Preparation",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "準備ができました。",
      example_reading: "じゅんびができました。",
      example_translation: "The preparation is done.",
      created_at: new Date().toISOString(),
    },
    {
      id: "104",
      word: "説明",
      reading: "せつめい",
      meaning: "Explanation",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "説明してください。",
      example_reading: "せつめいしてください。",
      example_translation: "Please explain.",
      created_at: new Date().toISOString(),
    },
    {
      id: "105",
      word: "連絡",
      reading: "れんらく",
      meaning: "Contact, Communication",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "連絡します。",
      example_reading: "れんらくします。",
      example_translation: "I will contact you.",
      created_at: new Date().toISOString(),
    },
    {
      id: "106",
      word: "予定",
      reading: "よてい",
      meaning: "Plan, Schedule",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "予定を確認します。",
      example_reading: "よていをかくにんします。",
      example_translation: "I check the schedule.",
      created_at: new Date().toISOString(),
    },
    {
      id: "107",
      word: "約束",
      reading: "やくそく",
      meaning: "Promise, Appointment",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "約束を守ります。",
      example_reading: "やくそくをまもります。",
      example_translation: "I keep my promise.",
      created_at: new Date().toISOString(),
    },
    {
      id: "108",
      word: "相談",
      reading: "そうだん",
      meaning: "Consultation",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "相談したいことがあります。",
      example_reading: "そうだんしたいことがあります。",
      example_translation: "I have something to consult about.",
      created_at: new Date().toISOString(),
    },
    {
      id: "109",
      word: "注意",
      reading: "ちゅうい",
      meaning: "Attention, Caution",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "注意してください。",
      example_reading: "ちゅういしてください。",
      example_translation: "Please be careful.",
      created_at: new Date().toISOString(),
    },
    {
      id: "110",
      word: "確認",
      reading: "かくにん",
      meaning: "Confirmation",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "確認が必要です。",
      example_reading: "かくにんがひつようです。",
      example_translation: "Confirmation is necessary.",
      created_at: new Date().toISOString(),
    },
    {
      id: "111",
      word: "変更",
      reading: "へんこう",
      meaning: "Change, Modification",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "予定を変更します。",
      example_reading: "よていをへんこうします。",
      example_translation: "I change the schedule.",
      created_at: new Date().toISOString(),
    },
    {
      id: "112",
      word: "決定",
      reading: "けってい",
      meaning: "Decision",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "決定しました。",
      example_reading: "けっていしました。",
      example_translation: "It has been decided.",
      created_at: new Date().toISOString(),
    },
    {
      id: "113",
      word: "選択",
      reading: "せんたく",
      meaning: "Choice, Selection",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "選択してください。",
      example_reading: "せんたくしてください。",
      example_translation: "Please choose.",
      created_at: new Date().toISOString(),
    },
    {
      id: "114",
      word: "比較",
      reading: "ひかく",
      meaning: "Comparison",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "比較します。",
      example_reading: "ひかくします。",
      example_translation: "I compare.",
      created_at: new Date().toISOString(),
    },
    {
      id: "115",
      word: "参加",
      reading: "さんか",
      meaning: "Participation",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "会議に参加します。",
      example_reading: "かいぎにさんかします。",
      example_translation: "I participate in the meeting.",
      created_at: new Date().toISOString(),
    },
    {
      id: "116",
      word: "協力",
      reading: "きょうりょく",
      meaning: "Cooperation",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "協力してください。",
      example_reading: "きょうりょくしてください。",
      example_translation: "Please cooperate.",
      created_at: new Date().toISOString(),
    },
    {
      id: "117",
      word: "努力",
      reading: "どりょく",
      meaning: "Effort",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "努力します。",
      example_reading: "どりょくします。",
      example_translation: "I make an effort.",
      created_at: new Date().toISOString(),
    },
    {
      id: "118",
      word: "成功",
      reading: "せいこう",
      meaning: "Success",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "成功しました。",
      example_reading: "せいこうしました。",
      example_translation: "It succeeded.",
      created_at: new Date().toISOString(),
    },
    {
      id: "119",
      word: "失敗",
      reading: "しっぱい",
      meaning: "Failure",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "失敗しました。",
      example_reading: "しっぱいしました。",
      example_translation: "It failed.",
      created_at: new Date().toISOString(),
    },
    {
      id: "120",
      word: "困難",
      reading: "こんなん",
      meaning: "Difficulty",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "困難な問題です。",
      example_reading: "こんなんなもんだいです。",
      example_translation: "It's a difficult problem.",
      created_at: new Date().toISOString(),
    },
    {
      id: "121",
      word: "簡単",
      reading: "かんたん",
      meaning: "Simple, Easy",
      level: "N4",
      part_of_speech: "Na-adjective",
      example_sentence: "簡単な問題です。",
      example_reading: "かんたんなもんだいです。",
      example_translation: "It's a simple problem.",
      created_at: new Date().toISOString(),
    },
    {
      id: "122",
      word: "複雑",
      reading: "ふくざつ",
      meaning: "Complex, Complicated",
      level: "N4",
      part_of_speech: "Na-adjective",
      example_sentence: "複雑な問題です。",
      example_reading: "ふくざつなもんだいです。",
      example_translation: "It's a complex problem.",
      created_at: new Date().toISOString(),
    },
    {
      id: "123",
      word: "重要",
      reading: "じゅうよう",
      meaning: "Important",
      level: "N4",
      part_of_speech: "Na-adjective",
      example_sentence: "重要な会議です。",
      example_reading: "じゅうようなかいぎです。",
      example_translation: "It's an important meeting.",
      created_at: new Date().toISOString(),
    },
  ],
  N3: [
    {
      id: "201",
      word: "議論",
      reading: "ぎろん",
      meaning: "Discussion, Debate",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "議論が続いています。",
      example_reading: "ぎろんがつづいています。",
      example_translation: "The discussion continues.",
      created_at: new Date().toISOString(),
    },
    {
      id: "202",
      word: "検討",
      reading: "けんとう",
      meaning: "Consideration, Examination",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "検討します。",
      example_reading: "けんとうします。",
      example_translation: "I will consider it.",
      created_at: new Date().toISOString(),
    },
    {
      id: "203",
      word: "提案",
      reading: "ていあん",
      meaning: "Proposal, Suggestion",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "提案があります。",
      example_reading: "ていあんがあります。",
      example_translation: "I have a proposal.",
      created_at: new Date().toISOString(),
    },
    {
      id: "204",
      word: "実施",
      reading: "じっし",
      meaning: "Implementation, Execution",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "計画を実施します。",
      example_reading: "けいかくをじっしします。",
      example_translation: "I implement the plan.",
      created_at: new Date().toISOString(),
    },
    {
      id: "205",
      word: "評価",
      reading: "ひょうか",
      meaning: "Evaluation, Assessment",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "評価が高いです。",
      example_reading: "ひょうかがたかいです。",
      example_translation: "The evaluation is high.",
      created_at: new Date().toISOString(),
    },
    {
      id: "206",
      word: "分析",
      reading: "ぶんせき",
      meaning: "Analysis",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "データを分析します。",
      example_reading: "データをぶんせきします。",
      example_translation: "I analyze the data.",
      created_at: new Date().toISOString(),
    },
    {
      id: "207",
      word: "調査",
      reading: "ちょうさ",
      meaning: "Investigation, Survey",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "調査を行います。",
      example_reading: "ちょうさをおこないます。",
      example_translation: "I conduct a survey.",
      created_at: new Date().toISOString(),
    },
    {
      id: "208",
      word: "研究",
      reading: "けんきゅう",
      meaning: "Research",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "研究しています。",
      example_reading: "けんきゅうしています。",
      example_translation: "I am researching.",
      created_at: new Date().toISOString(),
    },
    {
      id: "209",
      word: "開発",
      reading: "かいはつ",
      meaning: "Development",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "新製品を開発します。",
      example_reading: "しんせいひんをかいはつします。",
      example_translation: "I develop a new product.",
      created_at: new Date().toISOString(),
    },
    {
      id: "210",
      word: "改善",
      reading: "かいぜん",
      meaning: "Improvement",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "改善が必要です。",
      example_reading: "かいぜんがひつようです。",
      example_translation: "Improvement is necessary.",
      created_at: new Date().toISOString(),
    },
    {
      id: "211",
      word: "維持",
      reading: "いじ",
      meaning: "Maintenance",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "品質を維持します。",
      example_reading: "ひんしつをいじします。",
      example_translation: "I maintain the quality.",
      created_at: new Date().toISOString(),
    },
    {
      id: "212",
      word: "管理",
      reading: "かんり",
      meaning: "Management",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "プロジェクトを管理します。",
      example_reading: "プロジェクトをかんりします。",
      example_translation: "I manage the project.",
      created_at: new Date().toISOString(),
    },
    {
      id: "213",
      word: "運営",
      reading: "うんえい",
      meaning: "Operation, Management",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "会社を運営します。",
      example_reading: "かいしゃをうんえいします。",
      example_translation: "I operate the company.",
      created_at: new Date().toISOString(),
    },
    {
      id: "214",
      word: "経営",
      reading: "けいえい",
      meaning: "Management, Administration",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "経営が難しいです。",
      example_reading: "けいえいがむずかしいです。",
      example_translation: "Management is difficult.",
      created_at: new Date().toISOString(),
    },
    {
      id: "215",
      word: "戦略",
      reading: "せんりゃく",
      meaning: "Strategy",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "戦略を立てます。",
      example_reading: "せんりゃくをたてます。",
      example_translation: "I formulate a strategy.",
      created_at: new Date().toISOString(),
    },
    {
      id: "216",
      word: "方針",
      reading: "ほうしん",
      meaning: "Policy, Course",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "方針を決めます。",
      example_reading: "ほうしんをきめます。",
      example_translation: "I decide the policy.",
      created_at: new Date().toISOString(),
    },
    {
      id: "217",
      word: "目標",
      reading: "もくひょう",
      meaning: "Goal, Target",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "目標を達成します。",
      example_reading: "もくひょうをたっせいします。",
      example_translation: "I achieve the goal.",
      created_at: new Date().toISOString(),
    },
    {
      id: "218",
      word: "達成",
      reading: "たっせい",
      meaning: "Achievement, Accomplishment",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "達成しました。",
      example_reading: "たっせいしました。",
      example_translation: "I achieved it.",
      created_at: new Date().toISOString(),
    },
    {
      id: "219",
      word: "実現",
      reading: "じつげん",
      meaning: "Realization",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "夢を実現します。",
      example_reading: "ゆめをじつげんします。",
      example_translation: "I realize my dream.",
      created_at: new Date().toISOString(),
    },
    {
      id: "220",
      word: "進展",
      reading: "しんてん",
      meaning: "Progress, Development",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "進展がありました。",
      example_reading: "しんてんがありました。",
      example_translation: "There was progress.",
      created_at: new Date().toISOString(),
    },
    {
      id: "221",
      word: "発展",
      reading: "はってん",
      meaning: "Development, Growth",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "技術が発展します。",
      example_reading: "ぎじゅつがはってんします。",
      example_translation: "Technology develops.",
      created_at: new Date().toISOString(),
    },
    {
      id: "222",
      word: "成長",
      reading: "せいちょう",
      meaning: "Growth",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "会社が成長します。",
      example_reading: "かいしゃがせいちょうします。",
      example_translation: "The company grows.",
      created_at: new Date().toISOString(),
    },
  ],
  N2: [],
  N1: [],
}
