import { Word } from "./types";

/**
 * 테스트용 데이터
 */
export const mockWords: Record<string, Word[]> = {
  N5: [
    {
      id: "1",
      word: "こんにちは",
      reading: "こんにちは",
      meaning: "Hello, Good afternoon",
      level: "N5",
      part_of_speech: "Greeting",
      example_sentence: "こんにちは、元気ですか。",
      example_reading: "こんにちは、げんきですか。",
      example_translation: "Hello, how are you?",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      word: "ありがとう",
      reading: "ありがとう",
      meaning: "Thank you",
      level: "N5",
      part_of_speech: "Expression",
      example_sentence: "ありがとうございます。",
      example_reading: "ありがとうございます。",
      example_translation: "Thank you very much.",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      word: "学校",
      reading: "がっこう",
      meaning: "School",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "学校に行きます。",
      example_reading: "がっこうにいきます。",
      example_translation: "I go to school.",
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      word: "食べる",
      reading: "たべる",
      meaning: "To eat",
      level: "N5",
      part_of_speech: "Verb",
      example_sentence: "ご飯を食べます。",
      example_reading: "ごはんをたべます。",
      example_translation: "I eat rice.",
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      word: "水",
      reading: "みず",
      meaning: "Water",
      level: "N5",
      part_of_speech: "Noun",
      example_sentence: "水を飲みます。",
      example_reading: "みずをのみます。",
      example_translation: "I drink water.",
      created_at: new Date().toISOString(),
    },
  ],
  N4: [
    {
      id: "11",
      word: "経験",
      reading: "けいけん",
      meaning: "Experience",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "経験が必要です。",
      example_reading: "けいけんがひつようです。",
      example_translation: "Experience is necessary.",
      created_at: new Date().toISOString(),
    },
    {
      id: "12",
      word: "意見",
      reading: "いけん",
      meaning: "Opinion",
      level: "N4",
      part_of_speech: "Noun",
      example_sentence: "あなたの意見を聞かせてください。",
      example_reading: "あなたのいけんをきかせてください。",
      example_translation: "Please let me hear your opinion.",
      created_at: new Date().toISOString(),
    },
  ],
  N3: [
    {
      id: "21",
      word: "議論",
      reading: "ぎろん",
      meaning: "Discussion, Debate",
      level: "N3",
      part_of_speech: "Noun",
      example_sentence: "議論が続いています。",
      example_reading: "ぎろんがつづいています。",
      example_translation: "The discussion continues.",
      created_at: new Date().toISOString(),
    },
  ],
  N2: [],
  N1: [],
}
